/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API vendors */
        get: operations["get-api-vendors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vendors/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API vendors by slug */
        get: operations["get-api-vendors-by-slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BasicVendor: {
            mostEfficient: components["schemas"]["Item"];
            mostProfitable: components["schemas"]["Item"];
            mostVolume: components["schemas"]["Item"];
            name: string;
            /** @enum {string} */
            slug: "arbiters_of_hexis" | "cephalon_suda" | "new_loka" | "red_veil" | "steel_meridian" | "the_perrin_sequence";
        };
        BasicVendorsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/BasicVendorsResponseBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            updatedAtMs: number;
            updating: boolean;
            vendors: components["schemas"]["BasicVendor"][] | null;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Item: {
            name: string;
            /** Format: double */
            price: number;
            /** Format: double */
            score: number;
            slug: string;
            /** Format: int64 */
            standing: number;
            /** @enum {string} */
            type: "Mod" | "ArchPart" | "Weapon";
            /** Format: double */
            volume: number;
        };
        Vendor: {
            items: components["schemas"]["Item"][] | null;
            name: string;
            /** @enum {string} */
            slug: "arbiters_of_hexis" | "cephalon_suda" | "new_loka" | "red_veil" | "steel_meridian" | "the_perrin_sequence";
        };
        VendorsResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/api/schemas/VendorsResponseBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            updatedAtMs: number;
            updating: boolean;
            vendor: components["schemas"]["Vendor"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-api-vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasicVendorsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-vendors-by-slug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: "arbiters_of_hexis" | "cephalon_suda" | "new_loka" | "red_veil" | "steel_meridian" | "the_perrin_sequence";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorsResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
